### ISSUE TITLE
npm install @svgdotjs/svg.draggable.js fails with 404

### ISSUE THREAD

**Issue by frederic-schwarz** [svgdotjs/svg.draggable.js#103]
```bash
npm install @svgdotjs/svg.draggable.js
```
maybe I'm missing something but using the install notes from the readme fails
and results in:
```bash
npm ERR! code E404
npm ERR! 404 Not Found: @svgdotjs/svg.draggable.js@latest

npm ERR! A complete log of this run can be found in:
npm ERR!    /.npm/_logs/2019-01-25T14_08_06_721Z-debug.log
```
logs:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@svgdotjs/svg.draggable.js' ]
2 info using npm@6.4.1
3 info using node@v10.15.0
4 verbose npm-session 69543de893081d7a
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 http://registry.npmjs.org/@svgdotjs%2fsvg.draggable.js 1123ms
8 silly fetchPackageMetaData error for @svgdotjs/svg.draggable.js@latest 404 Not Found: @svgdotjs/svg.draggable.js@latest
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 2639ms
11 verbose stack Error: 404 Not Found: @svgdotjs/svg.draggable.js@latest
11 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
11 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
11 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
11 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
11 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
11 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
11 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
11 verbose stack     at runCallback (timers.js:705:18)
11 verbose stack     at tryOnImmediate (timers.js:676:5)
11 verbose stack     at processImmediate (timers.js:658:5)
12 verbose cwd ...
13 verbose Darwin 18.0.0
14 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@svgdotjs/svg.draggable.js"
15 verbose node v10.15.0
16 verbose npm  v6.4.1
17 error code E404
18 error 404 Not Found: @svgdotjs/svg.draggable.js@latest
19 verbose exit [ 1, true ]
```

installing it directly from github works
```
npm install svgdotjs/svg.draggable.js
```

**Comment by Fuzzyma** [comment]
Ai that's bad. I forgot to update the package name in the package.json.

So for now just npm i svg.draggable.js should work.
I am on vacation right now so I can't fix it. Next Friday I will publish under the correct name and remove the wrongly published one.

**Comment by frederic-schwarz** [comment]
Thx and enjoy your vacation!
